defaults: &defaults
  host: 'http://localhost:3000'
  sitename: 'ラペコ'
  admin:
    username: <%= ENV['ADMIN_USERNAME'] %>
    password: <%= ENV['ADMIN_PASSWORD'] %>

development:
  <<: *defaults
  host: 'http://localhost:3000'
  twitpic:
    api_key: <%= ENV['TWITPIC_API_KEY'] %>
  twitter:
    app:
      oauth_consumer_key: <%= ENV['OAUTH_CONSUMER_KEY'] %>
      oauth_consumer_secret: <%= ENV['OAUTH_CONSUMER_SECRET'] %>
    app_user: <%= ENV['TWITTER_APP_USER'] %>
    upload_user: <%= ENV['TWITTER_UPLOAD_USER'] %>
    hashtag: pecora

test:
  <<: *defaults

production:
  <<: *defaults
  host: 'http://rapeco.jp'
  admin:
    username: <%= ENV['ADMIN_USERNAME'] %>
    password: <%= ENV['ADMIN_PASSWORD'] %>
  twitpic:
    api_key: <%= ENV['TWITPIC_API_KEY'] %>
  twitter:
    app:
      oauth_consumer_key: <%= ENV['OAUTH_CONSUMER_KEY'] %>
      oauth_consumer_secret: <%= ENV['OAUTH_CONSUMER_SECRET'] %>
    hashtag: rapeco
    app_user: <%= ENV['TWITTER_APP_USER'] %>
    upload_user: <%= ENV['TWITTER_UPLOAD_USER'] %>
